// Dashboard Widgets Index
export { LeaveBalanceWidget } from './LeaveBalanceWidget'
export { MyProjectsWidget } from './MyProjectsWidget'
export { AnimalsOnMedicationWidget } from './AnimalsOnMedicationWidget'
export { VetCommentsWidget } from './VetCommentsWidget'
export { StaffAttendanceWidget } from './StaffAttendanceWidget'
export { CalendarWidget } from './CalendarWidget'
export { QuickActionsWidget } from './QuickActionsWidget'
export { GoogleCalendarEventsWidget } from './GoogleCalendarEventsWidget'
export { CalendarEventList } from './CalendarEventList'
export { CalendarWeekGrid } from './CalendarWeekGrid'
export * from './calendarWeek'
export * from './widgetConfig'
export { RoleWelcomeGuide } from './RoleWelcomeGuide'
