/**
 * Guest Demo Mode — GLP 合規模組靜態範例資料
 *
 * 涵蓋 8 個 GLP 頁面：文件控制、變更控制、風險登記簿、管理審查、
 * 配製紀錄、能力評鑑、研究最終報告、環境監控（含監控點讀值子資源）。
 *
 * 全部為虛構示範資料，沿用專案既有 guest demo 風格
 * （`範例…` 標題、`demo-` 前綴 UUID、`*@example.com`、2025 年日期）。
 * 型別定義來源：`@/lib/api/glpCompliance`。
 */
import type {
  ControlledDocument,
  ChangeRequest,
  RiskEntry,
  ManagementReview,
  FormulationRecord,
  CompetencyAssessment,
  StudyFinalReport,
  MonitoringPoint,
  EnvironmentReading,
} from '@/lib/api/glpCompliance'

// ============================================================
// 文件控制（Controlled Documents）— GET /admin/documents
// ============================================================

export const DEMO_CONTROLLED_DOCUMENTS: ControlledDocument[] = [
  {
    id: 'demo-doc-1',
    doc_number: 'QM-001',
    title: '範例品質手冊（示範資料）',
    doc_type: 'quality_manual',
    category: '品質系統',
    current_version: 3,
    status: 'active',
    effective_date: '2025-01-01',
    review_due_date: '2026-01-01',
    owner_id: 'demo-u1',
    owner_name: '範例品保主管',
    approved_by: 'demo-u2',
    approved_at: '2024-12-20T02:00:00Z',
    retention_years: 10,
    created_at: '2024-12-01T00:00:00Z',
    updated_at: '2024-12-20T02:00:00Z',
  },
  {
    id: 'demo-doc-2',
    doc_number: 'SOP-014',
    title: '範例動物飼育標準作業程序（示範資料）',
    doc_type: 'sop',
    category: '動物照護',
    current_version: 2,
    status: 'active',
    effective_date: '2025-02-15',
    review_due_date: '2026-02-15',
    owner_id: 'demo-u3',
    owner_name: '範例獸醫',
    approved_by: 'demo-u2',
    approved_at: '2025-02-10T03:30:00Z',
    retention_years: 7,
    created_at: '2025-01-20T00:00:00Z',
    updated_at: '2025-02-10T03:30:00Z',
  },
  {
    id: 'demo-doc-3',
    doc_number: 'SOP-027',
    title: '範例試驗物質配製標準作業程序（示範資料）',
    doc_type: 'sop',
    category: '試驗操作',
    current_version: 1,
    status: 'under_review',
    effective_date: null,
    review_due_date: null,
    owner_id: 'demo-u4',
    owner_name: '範例研究員',
    approved_by: null,
    approved_at: null,
    retention_years: 7,
    created_at: '2025-03-05T00:00:00Z',
    updated_at: '2025-03-05T00:00:00Z',
  },
  {
    id: 'demo-doc-4',
    doc_number: 'FRM-006',
    title: '範例環境監控紀錄表（示範資料）',
    doc_type: 'form',
    category: '設施環境',
    current_version: 1,
    status: 'draft',
    effective_date: null,
    review_due_date: null,
    owner_id: 'demo-u1',
    owner_name: '範例品保主管',
    approved_by: null,
    approved_at: null,
    retention_years: 5,
    created_at: '2025-03-18T00:00:00Z',
    updated_at: '2025-03-18T00:00:00Z',
  },
]

// ============================================================
// 變更控制（Change Requests）— GET /admin/change-requests
// ============================================================

export const DEMO_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 'demo-chg-1',
    change_number: 'CR-2025-001',
    title: '範例更換高壓滅菌器（示範資料）',
    change_type: 'equipment',
    description: '將 A 棟舊型高壓滅菌器汰換為新型號，提升滅菌效率與紀錄追溯能力。',
    justification: '舊型設備已逾使用年限，校正結果偏移增加。',
    impact_assessment: '影響動物房消毒排程，需同步更新 SOP-014。',
    status: 'approved',
    requested_by: 'demo-u3',
    requester_name: '範例獸醫',
    approved_by: 'demo-u2',
    approved_at: '2025-02-28T06:00:00Z',
    created_at: '2025-02-10T00:00:00Z',
    updated_at: '2025-02-28T06:00:00Z',
  },
  {
    id: 'demo-chg-2',
    change_number: 'CR-2025-002',
    title: '範例修訂血液採樣方法（示範資料）',
    change_type: 'method',
    description: '調整採血點與採樣量上限，符合最新動物福祉指引。',
    justification: '降低受試動物採樣負擔，提升 3R 落實程度。',
    impact_assessment: '需重新訓練相關人員並更新能力評鑑。',
    status: 'under_review',
    requested_by: 'demo-u4',
    requester_name: '範例研究員',
    approved_by: null,
    approved_at: null,
    created_at: '2025-03-12T00:00:00Z',
    updated_at: '2025-03-15T00:00:00Z',
  },
  {
    id: 'demo-chg-3',
    change_number: 'CR-2025-003',
    title: '範例新增夜間值班人員（示範資料）',
    change_type: 'personnel',
    description: '增設夜間值班獸醫技術員一名，加強術後動物監測。',
    justification: '術後首夜為關鍵觀察期，需即時處置。',
    impact_assessment: '影響排班表與人事預算，無 GLP 系統性風險。',
    status: 'draft',
    requested_by: 'demo-u1',
    requester_name: '範例品保主管',
    approved_by: null,
    approved_at: null,
    created_at: '2025-03-20T00:00:00Z',
    updated_at: '2025-03-20T00:00:00Z',
  },
]

// ============================================================
// 風險登記簿（Risk Register）— GET /admin/risks
// ============================================================

export const DEMO_RISKS: RiskEntry[] = [
  {
    id: 'demo-risk-1',
    risk_number: 'RISK-2025-001',
    title: '範例冷藏樣本溫度失控（示範資料）',
    description: '停電或冰箱故障導致生物樣本溫度超出範圍，影響資料完整性。',
    category: 'technical',
    source: '設備可靠度分析',
    severity: 4,
    likelihood: 2,
    detectability: 3,
    risk_score: 24,
    status: 'mitigated',
    mitigation_plan: '加裝溫度監控警報並建置備援電源，超標即簡訊通知值班人員。',
    residual_risk_score: 8,
    owner_id: 'demo-u1',
    owner_name: '範例品保主管',
    review_date: '2025-09-30',
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-02-20T00:00:00Z',
  },
  {
    id: 'demo-risk-2',
    risk_number: 'RISK-2025-002',
    title: '範例人員資格逾期未重評（示範資料）',
    description: '關鍵操作人員能力評鑑到期未及時重新評鑑，導致 GLP 合規缺口。',
    category: 'compliance',
    source: '內部稽核發現',
    severity: 3,
    likelihood: 3,
    detectability: 2,
    risk_score: 18,
    status: 'identified',
    mitigation_plan: null,
    residual_risk_score: null,
    owner_id: 'demo-u2',
    owner_name: '範例研究主持人',
    review_date: '2025-06-30',
    created_at: '2025-02-05T00:00:00Z',
    updated_at: '2025-02-05T00:00:00Z',
  },
  {
    id: 'demo-risk-3',
    risk_number: 'RISK-2025-003',
    title: '範例試驗物質誤標（示範資料）',
    description: '配製標籤與批號輸入錯誤，可能造成給藥劑量偏差。',
    category: 'safety',
    source: '配製流程 FMEA',
    severity: 5,
    likelihood: 1,
    detectability: 2,
    risk_score: 10,
    status: 'accepted',
    mitigation_plan: '導入雙人覆核與條碼掃描，殘餘風險可接受。',
    residual_risk_score: 4,
    owner_id: 'demo-u4',
    owner_name: '範例研究員',
    review_date: '2025-12-31',
    created_at: '2025-02-18T00:00:00Z',
    updated_at: '2025-03-01T00:00:00Z',
  },
]

// ============================================================
// 管理審查（Management Reviews）— GET /admin/management-reviews
// ============================================================

export const DEMO_MANAGEMENT_REVIEWS: ManagementReview[] = [
  {
    id: 'demo-mr-1',
    review_number: 'MR-2025-Q1',
    title: '範例第一季管理審查會議（示範資料）',
    review_date: '2025-03-28',
    status: 'completed',
    agenda: '1. 前次行動項目追蹤 2. 稽核結果回顧 3. 風險登記簿檢討 4. 資源需求',
    attendees: [
      { name: '範例研究主持人', role: 'PI' },
      { name: '範例品保主管', role: 'QAU' },
      { name: '範例獸醫', role: 'VET' },
    ],
    minutes: '會議通過本季稽核改善計畫，並核定新增夜間值班人員之資源申請。',
    decisions: ['核定夜間值班人員增補', '要求於下季完成 SOP-014 改版'],
    action_items: [
      { item: '完成 SOP-014 改版', owner: '範例獸醫', due: '2025-05-31' },
      { item: '執行溫控警報驗證', owner: '範例品保主管', due: '2025-04-30' },
    ],
    chaired_by: 'demo-u2',
    approved_at: '2025-04-02T01:00:00Z',
    created_at: '2025-03-20T00:00:00Z',
    updated_at: '2025-04-02T01:00:00Z',
  },
  {
    id: 'demo-mr-2',
    review_number: 'MR-2025-Q2',
    title: '範例第二季管理審查會議（示範資料）',
    review_date: '2025-06-27',
    status: 'planned',
    agenda: '1. 第一季行動項目結案 2. 環境監控趨勢 3. 能力評鑑到期清單',
    attendees: null,
    minutes: null,
    decisions: null,
    action_items: null,
    chaired_by: 'demo-u2',
    approved_at: null,
    created_at: '2025-04-10T00:00:00Z',
    updated_at: '2025-04-10T00:00:00Z',
  },
]

// ============================================================
// 配製紀錄（Formulation Records）— GET /admin/formulation-records
// ============================================================

export const DEMO_FORMULATION_RECORDS: FormulationRecord[] = [
  {
    id: 'demo-form-1',
    product_id: 'demo-prod-1',
    product_name: '範例試驗物質 A（示範資料）',
    protocol_id: 'demo-p1',
    formulation_date: '2025-03-01',
    batch_number: 'LOT-2025-0301',
    concentration: '10 mg/mL',
    volume: '250 mL',
    prepared_by: 'demo-u4',
    preparer_name: '範例研究員',
    verified_by: 'demo-u3',
    verified_at: '2025-03-01T05:00:00Z',
    expiry_date: '2025-03-31',
    notes: '以無菌生理食鹽水配製，配製後 4°C 冷藏保存。',
    created_at: '2025-03-01T04:30:00Z',
  },
  {
    id: 'demo-form-2',
    product_id: 'demo-prod-2',
    product_name: '範例對照溶液（示範資料）',
    protocol_id: 'demo-p1',
    formulation_date: '2025-03-01',
    batch_number: 'LOT-2025-0302',
    concentration: '0 mg/mL（賦形劑對照）',
    volume: '250 mL',
    prepared_by: 'demo-u4',
    preparer_name: '範例研究員',
    verified_by: 'demo-u3',
    verified_at: '2025-03-01T05:10:00Z',
    expiry_date: '2025-03-31',
    notes: '僅含賦形劑，供對照組使用。',
    created_at: '2025-03-01T04:40:00Z',
  },
  {
    id: 'demo-form-3',
    product_id: 'demo-prod-1',
    product_name: '範例試驗物質 A（示範資料）',
    protocol_id: null,
    formulation_date: '2025-03-15',
    batch_number: 'LOT-2025-0315',
    concentration: '5 mg/mL',
    volume: '100 mL',
    prepared_by: 'demo-u4',
    preparer_name: '範例研究員',
    verified_by: null,
    verified_at: null,
    expiry_date: '2025-04-14',
    notes: '待第二人覆核。',
    created_at: '2025-03-15T06:00:00Z',
  },
]

// ============================================================
// 能力評鑑（Competency Assessments）— GET /admin/competency-assessments
// ============================================================

export const DEMO_COMPETENCY_ASSESSMENTS: CompetencyAssessment[] = [
  {
    id: 'demo-comp-1',
    user_id: 'demo-u4',
    user_name: '範例研究員',
    assessment_type: 'initial',
    skill_area: '靜脈採血技術',
    assessment_date: '2025-01-20',
    assessor_id: 'demo-u3',
    assessor_name: '範例獸醫',
    result: 'competent',
    score: 92,
    method: 'practical_test',
    valid_until: '2026-01-20',
    notes: '操作熟練，符合動物福祉要求。',
    created_at: '2025-01-20T00:00:00Z',
  },
  {
    id: 'demo-comp-2',
    user_id: 'demo-u3',
    user_name: '範例獸醫',
    assessment_type: 'periodic',
    skill_area: '外科手術無菌操作',
    assessment_date: '2025-02-12',
    assessor_id: 'demo-u2',
    assessor_name: '範例研究主持人',
    result: 'competent',
    score: 96,
    method: 'observation',
    valid_until: '2026-02-12',
    notes: null,
    created_at: '2025-02-12T00:00:00Z',
  },
  {
    id: 'demo-comp-3',
    user_id: 'demo-u5',
    user_name: '範例技術員',
    assessment_type: 'initial',
    skill_area: '試驗物質配製',
    assessment_date: '2025-03-05',
    assessor_id: 'demo-u4',
    assessor_name: '範例研究員',
    result: 'requires_supervision',
    score: 74,
    method: 'practical_test',
    valid_until: '2025-09-05',
    notes: '基本操作正確，濃度計算需在監督下執行。',
    created_at: '2025-03-05T00:00:00Z',
  },
  {
    id: 'demo-comp-4',
    user_id: 'demo-u6',
    user_name: '範例新進助理',
    assessment_type: 'requalification',
    skill_area: '動物保定操作',
    assessment_date: '2025-03-18',
    assessor_id: 'demo-u3',
    assessor_name: '範例獸醫',
    result: 'not_yet_competent',
    score: 58,
    method: 'written_test',
    valid_until: null,
    notes: '需再訓練後重新評鑑。',
    created_at: '2025-03-18T00:00:00Z',
  },
]

// ============================================================
// 研究最終報告（Study Final Reports）— GET /admin/study-reports
// ============================================================

export const DEMO_STUDY_REPORTS: StudyFinalReport[] = [
  {
    id: 'demo-sr-1',
    report_number: 'SR-2025-001',
    protocol_id: 'demo-p1',
    title: '範例異種移植耐受性研究最終報告（示範資料）',
    status: 'signed',
    summary: '本研究評估範例試驗物質 A 於研究豬之耐受性與安全性。',
    methods: '採隨機分組，試驗組與賦形劑對照組各半，觀察期 28 天。',
    results: '試驗組未見顯著不良反應，體重變化與對照組無統計差異。',
    conclusions: '於本試驗條件下，範例試驗物質 A 具良好耐受性。',
    deviations: '第 14 天一次體重量測延後 2 小時，經評估不影響資料完整性。',
    signed_by: 'demo-u2',
    signed_at: '2025-03-30T07:00:00Z',
    qau_statement: '本報告經品保單位查核，忠實反映原始數據並符合 GLP 規範。',
    qau_signed_by: 'demo-u1',
    qau_signed_at: '2025-03-31T02:00:00Z',
    created_at: '2025-03-10T00:00:00Z',
    updated_at: '2025-03-31T02:00:00Z',
  },
  {
    id: 'demo-sr-2',
    report_number: 'SR-2025-002',
    protocol_id: 'demo-p1',
    title: '範例術後照護成效研究最終報告（示範資料）',
    status: 'under_review',
    summary: '評估範例術後照護方案對恢復期之影響。',
    methods: '回溯性比較兩種照護排程下之恢復指標。',
    results: '數據分析中，初步顯示夜間監測組併發症較低。',
    conclusions: null,
    deviations: null,
    signed_by: null,
    signed_at: null,
    qau_statement: null,
    qau_signed_by: null,
    qau_signed_at: null,
    created_at: '2025-03-22T00:00:00Z',
    updated_at: '2025-03-26T00:00:00Z',
  },
]

// ============================================================
// 環境監控（Environment Monitoring）
//   GET /admin/env-monitoring/points   → 監控點
//   GET /admin/env-monitoring/readings → 讀值（子資源）
// ============================================================

export const DEMO_MONITORING_POINTS: MonitoringPoint[] = [
  {
    id: 'demo-mp-1',
    name: '範例 A 棟動物房（示範資料）',
    location_type: 'animal_room',
    building_id: 'demo-bld-a',
    zone_id: 'demo-zone-a1',
    parameters: [
      { name: '溫度', unit: '°C', min: 20, max: 26 },
      { name: '相對濕度', unit: '%', min: 40, max: 70 },
    ],
    monitoring_interval: 'continuous',
    is_active: true,
    created_at: '2025-01-05T00:00:00Z',
    updated_at: '2025-01-05T00:00:00Z',
  },
  {
    id: 'demo-mp-2',
    name: '範例試驗物質冷藏庫（示範資料）',
    location_type: 'storage',
    building_id: 'demo-bld-a',
    zone_id: null,
    parameters: [{ name: '溫度', unit: '°C', min: 2, max: 8 }],
    monitoring_interval: 'hourly',
    is_active: true,
    created_at: '2025-01-05T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
  {
    id: 'demo-mp-3',
    name: '範例配製無塵室（示範資料）',
    location_type: 'clean_room',
    building_id: 'demo-bld-b',
    zone_id: 'demo-zone-b2',
    parameters: [
      { name: '溫度', unit: '°C', min: 18, max: 24 },
      { name: '壓差', unit: 'Pa', min: 10, max: 30 },
    ],
    monitoring_interval: 'daily',
    is_active: false,
    created_at: '2025-01-08T00:00:00Z',
    updated_at: '2025-03-01T00:00:00Z',
  },
]

export const DEMO_ENVIRONMENT_READINGS: EnvironmentReading[] = [
  {
    id: 'demo-rd-1',
    monitoring_point_id: 'demo-mp-1',
    reading_time: '2025-03-20T08:00:00Z',
    readings: { 溫度: 22.4, 相對濕度: 55 },
    is_out_of_range: false,
    out_of_range_params: null,
    recorded_by: 'demo-u5',
    source: 'manual',
    notes: null,
    created_at: '2025-03-20T08:05:00Z',
  },
  {
    id: 'demo-rd-2',
    monitoring_point_id: 'demo-mp-1',
    reading_time: '2025-03-20T14:00:00Z',
    readings: { 溫度: 26.8, 相對濕度: 58 },
    is_out_of_range: true,
    out_of_range_params: ['溫度'],
    recorded_by: null,
    source: 'sensor',
    notes: '午後空調負載偏高，已通報設施人員。',
    created_at: '2025-03-20T14:01:00Z',
  },
  {
    id: 'demo-rd-3',
    monitoring_point_id: 'demo-mp-2',
    reading_time: '2025-03-20T09:00:00Z',
    readings: { 溫度: 4.6 },
    is_out_of_range: false,
    out_of_range_params: null,
    recorded_by: 'demo-u5',
    source: 'manual',
    notes: null,
    created_at: '2025-03-20T09:02:00Z',
  },
]
