// 事件類別對應中文
export const categoryLabels: Record<string, string> = {
  ERP: 'ERP',
  AUP: '計畫書',
  ANIMAL: '實驗動物',
  SYSTEM: '系統',
  // 補全：user_activity_logs 實際出現的 event_category（先前缺，稽核類別會露原文）
  ADMIN: '系統管理',
  AUDIT: '稽核',
  EQUIPMENT: '設施設備',
  HR: '人員管理',
  MESSAGING: '站內信',
  PLANNED_EXPERIMENT: '試驗規劃',
  PROTOCOL_TEMPLATE: '計畫書範本',
  SECURITY: '安全',
}

// 事件類型對應中文顯示
export const eventTypeLabels: Record<string, { label: string; color: string }> = {
  // 通用操作
  DOC_CREATE: { label: '建立單據', color: 'bg-status-success-text' },
  DOC_UPDATE: { label: '更新單據', color: 'bg-status-info-text' },
  DOC_DELETE: { label: '刪除單據', color: 'bg-status-error-text' },
  DOC_SUBMIT: { label: '送審單據', color: 'bg-status-warning-text' },
  DOC_APPROVE: { label: '核准單據', color: 'bg-status-purple-text' },
  DOC_CANCEL: { label: '作廢單據', color: 'bg-status-neutral-text' },
  PARTNER_CREATE: { label: '建立夥伴', color: 'bg-status-success-text' },
  PARTNER_UPDATE: { label: '更新夥伴', color: 'bg-status-info-text' },
  PARTNER_DELETE: { label: '刪除夥伴', color: 'bg-status-error-text' },
  PRODUCT_CREATE: { label: '建立產品', color: 'bg-status-success-text' },
  PRODUCT_UPDATE: { label: '更新產品', color: 'bg-status-info-text' },
  PRODUCT_DELETE: { label: '刪除產品', color: 'bg-status-error-text' },
  CATEGORY_CREATE: { label: '建立分類', color: 'bg-status-success-text' },
  WAREHOUSE_CREATE: { label: '建立倉庫', color: 'bg-status-success-text' },
  WAREHOUSE_UPDATE: { label: '更新倉庫', color: 'bg-status-info-text' },
  WAREHOUSE_DELETE: { label: '刪除倉庫', color: 'bg-status-error-text' },
  ROLE_CREATE: { label: '建立角色', color: 'bg-status-success-text' },
  ROLE_UPDATE: { label: '更新角色', color: 'bg-status-info-text' },
  ROLE_DELETE: { label: '刪除角色', color: 'bg-status-error-text' },
  // 動物管理
  ANIMAL_CREATE: { label: '建立動物', color: 'bg-status-success-text' },
  ANIMAL_UPDATE: { label: '更新動物', color: 'bg-status-info-text' },
  ANIMAL_DELETE: { label: '刪除動物', color: 'bg-status-error-text' },
  ANIMAL_BATCH_ASSIGN: { label: '批次分配', color: 'bg-status-purple-text' },
  OBSERVATION_CREATE: { label: '建立觀察', color: 'bg-status-success-text' },
  OBSERVATION_UPDATE: { label: '更新觀察', color: 'bg-status-info-text' },
  OBSERVATION_DELETE: { label: '刪除觀察', color: 'bg-status-error-text' },
  SURGERY_CREATE: { label: '建立手術', color: 'bg-status-success-text' },
  SURGERY_UPDATE: { label: '更新手術', color: 'bg-status-info-text' },
  SURGERY_DELETE: { label: '刪除手術', color: 'bg-status-error-text' },
  WEIGHT_CREATE: { label: '記錄體重', color: 'bg-status-success-text' },
  WEIGHT_UPDATE: { label: '更新體重', color: 'bg-status-info-text' },
  WEIGHT_DELETE: { label: '刪除體重', color: 'bg-status-error-text' },
  VACCINATION_CREATE: { label: '建立疫苗', color: 'bg-status-success-text' },
  VACCINATION_UPDATE: { label: '更新疫苗', color: 'bg-status-info-text' },
  VACCINATION_DELETE: { label: '刪除疫苗', color: 'bg-status-error-text' },
  SACRIFICE_UPSERT: { label: '犧牲/安樂死', color: 'bg-audit-sacrifice' },
  PATHOLOGY_UPSERT: { label: '病理報告', color: 'bg-status-purple-text' },
  VET_RECOMMENDATION_ADD: { label: '獸醫建議', color: 'bg-audit-medical' },
  MEDICAL_EXPORT: { label: '匯出醫療資料', color: 'bg-audit-medical' },
  BLOOD_TEST_CREATE: { label: '建立血液檢查', color: 'bg-status-success-text' },
  BLOOD_TEST_UPDATE: { label: '更新血液檢查', color: 'bg-status-info-text' },
  BLOOD_TEST_DELETE: { label: '刪除血液檢查', color: 'bg-status-error-text' },
  TEMPLATE_CREATE: { label: '建立模板', color: 'bg-status-success-text' },
  TEMPLATE_UPDATE: { label: '更新模板', color: 'bg-status-info-text' },
  TEMPLATE_DELETE: { label: '刪除模板', color: 'bg-status-error-text' },
  PANEL_CREATE: { label: '建立組合', color: 'bg-status-success-text' },
  PANEL_UPDATE: { label: '更新組合', color: 'bg-status-info-text' },
  PANEL_DELETE: { label: '刪除組合', color: 'bg-status-error-text' },
  // 計畫書
  PROTOCOL_CREATE: { label: '建立計畫書', color: 'bg-audit-protocol' },
  PROTOCOL_UPDATE: { label: '更新計畫書', color: 'bg-audit-protocol' },
  PROTOCOL_SUBMIT: { label: '送審計畫書', color: 'bg-audit-protocol' },
  PROTOCOL_APPROVE: { label: '核准計畫書', color: 'bg-audit-protocol' },
  PROTOCOL_REJECT: { label: '駁回計畫書', color: 'bg-status-error-text' },
  PROTOCOL_STATUS_CHANGE: { label: '狀態變更', color: 'bg-audit-protocol' },
  PROTOCOL_REVIEWER_ASSIGN: { label: '指派審查委員', color: 'bg-audit-protocol' },
  PROTOCOL_IMPORT_APPROVED: { label: '核准匯入計畫書', color: 'bg-audit-protocol' },
  PROTOCOL_IMPORT_FINALIZED: { label: '完成匯入計畫書', color: 'bg-audit-protocol' },
  PROTOCOL_IMPORT_REVIEWS_RECORDED: { label: '記錄匯入審查', color: 'bg-audit-protocol' },
  PROTOCOL_DELETED: { label: '刪除計畫書', color: 'bg-status-error-text' },
  PROTOCOL_SOFT_DELETED: { label: '停用計畫書', color: 'bg-status-neutral-text' },
  PROTOCOL_PI_PROVISIONED: { label: '開通計畫主持人', color: 'bg-audit-protocol' },
  PI_INVITE_SEND: { label: '寄送主持人邀請', color: 'bg-status-info-text' },
  // 計畫修正案
  AMENDMENT_CLASSIFY_MINOR: { label: '判定為次要修正', color: 'bg-status-info-text' },
  AMENDMENT_CLASSIFY_MAJOR: { label: '判定為重大修正', color: 'bg-status-warning-text' },
  AMENDMENT_REVISION_REQUIRED: { label: '要求修正案補正', color: 'bg-status-warning-text' },
  AMENDMENT_EFFECTIVE: { label: '修正案生效', color: 'bg-status-purple-text' },
  AMENDMENT_IMPORT_BACKFILLED: { label: '補建匯入修正案', color: 'bg-status-info-text' },
  AMENDMENT_IMPORT_FINALIZED: { label: '完成匯入修正案', color: 'bg-status-info-text' },
  AMENDMENT_IMPORT_REVIEWS_RECORDED: { label: '記錄修正案審查', color: 'bg-status-info-text' },
  // 登入 / 安全
  LOGIN_SUCCESS: { label: '登入成功', color: 'bg-status-success-text' },
  LOGIN_FAILED: { label: '登入失敗', color: 'bg-status-error-text' },
  LOGOUT: { label: '登出', color: 'bg-status-neutral-text' },
  FORCE_LOGOUT: { label: '強制登出', color: 'bg-status-error-text' },
  IMPERSONATE_START: { label: '開始代理登入', color: 'bg-status-warning-text' },
  PASSWORD_SELF_CHANGE: { label: '變更密碼', color: 'bg-status-info-text' },
  PASSWORD_ADMIN_RESET: { label: '管理員重設密碼', color: 'bg-status-warning-text' },
  PASSWORD_TOKEN_RESET: { label: '重設密碼', color: 'bg-status-info-text' },
  TWO_FACTOR_ENABLED: { label: '啟用兩步驟驗證', color: 'bg-status-success-text' },
  TWO_FACTOR_DISABLED: { label: '停用兩步驟驗證', color: 'bg-status-warning-text' },
  IP_BLOCKLIST_ADD: { label: '封鎖 IP', color: 'bg-status-error-text' },
  IP_BLOCKLIST_UNBLOCK: { label: '解除 IP 封鎖', color: 'bg-status-success-text' },
  SIGNATURE_CREATE: { label: '電子簽章', color: 'bg-status-purple-text' },
  // 使用者 / 角色
  USER_CREATE: { label: '建立使用者', color: 'bg-status-success-text' },
  USER_UPDATE: { label: '更新使用者', color: 'bg-status-info-text' },
  USER_STATUS_CHANGE: { label: '使用者狀態變更', color: 'bg-status-info-text' },
  USER_ROLE_CHANGE: { label: '使用者角色變更', color: 'bg-status-info-text' },
  USER_DEPARTMENT_CHANGE: { label: '使用者部門變更', color: 'bg-status-info-text' },
  USER_DEACTIVATE_SELF: { label: '停用本人帳號', color: 'bg-status-warning-text' },
  USER_DELETE: { label: '刪除使用者', color: 'bg-status-error-text' },
  ROLE_PERMISSION_CHANGE: { label: '角色權限變更', color: 'bg-status-info-text' },
  ROLE_DEACTIVATE: { label: '停用角色', color: 'bg-status-warning-text' },
  AI_API_KEY_CREATE: { label: '建立 AI 金鑰', color: 'bg-status-success-text' },
  AI_API_KEY_DELETE: { label: '刪除 AI 金鑰', color: 'bg-status-error-text' },
  // HR — 請假
  LEAVE_CREATE: { label: '建立請假', color: 'bg-status-success-text' },
  LEAVE_UPDATE: { label: '更新請假', color: 'bg-status-info-text' },
  LEAVE_DELETE: { label: '刪除請假', color: 'bg-status-error-text' },
  LEAVE_SUBMIT: { label: '送出請假', color: 'bg-status-warning-text' },
  LEAVE_PROXY_CONFIRM: { label: '代理人確認', color: 'bg-status-purple-text' },
  LEAVE_PROXY_REJECT: { label: '代理人駁回', color: 'bg-status-error-text' },
  LEAVE_APPROVE_INTERIM: { label: '初步核准請假', color: 'bg-status-purple-text' },
  LEAVE_APPROVE_FINAL: { label: '核准請假', color: 'bg-status-purple-text' },
  LEAVE_APPROVE_INTERIM_OVERRIDE: { label: '初步核准請假（覆核）', color: 'bg-status-purple-text' },
  LEAVE_APPROVE_FINAL_OVERRIDE: { label: '核准請假（覆核）', color: 'bg-status-purple-text' },
  LEAVE_REJECT: { label: '駁回請假', color: 'bg-status-error-text' },
  LEAVE_CANCEL: { label: '取消請假', color: 'bg-status-neutral-text' },
  LEAVE_CANCEL_RETROACTIVE: { label: '追溯取消請假', color: 'bg-status-neutral-text' },
  // HR — 加班
  OVERTIME_CREATE: { label: '建立加班', color: 'bg-status-success-text' },
  OVERTIME_UPDATE: { label: '更新加班', color: 'bg-status-info-text' },
  OVERTIME_DELETE: { label: '刪除加班', color: 'bg-status-error-text' },
  OVERTIME_SUBMIT: { label: '送出加班', color: 'bg-status-warning-text' },
  OVERTIME_APPROVE_INTERIM: { label: '初步核准加班', color: 'bg-status-purple-text' },
  OVERTIME_APPROVE_FINAL: { label: '核准加班', color: 'bg-status-purple-text' },
  OVERTIME_REJECT: { label: '駁回加班', color: 'bg-status-error-text' },
  OVERTIME_VOID: { label: '作廢加班', color: 'bg-status-error-text' },
  COMP_TIME_REVOKE: { label: '收回補休', color: 'bg-status-error-text' },
  // HR — 出勤 / 特休
  ATTENDANCE_CLOCK_IN: { label: '上班打卡', color: 'bg-status-success-text' },
  ATTENDANCE_CLOCK_OUT: { label: '下班打卡', color: 'bg-status-info-text' },
  ATTENDANCE_CLOCK_IN_DENIED: { label: '上班打卡遭拒', color: 'bg-status-error-text' },
  ATTENDANCE_CLOCK_OUT_DENIED: { label: '下班打卡遭拒', color: 'bg-status-error-text' },
  ATTENDANCE_CORRECT: { label: '出勤更正', color: 'bg-status-warning-text' },
  ANNUAL_LEAVE_CREATE: { label: '建立特休', color: 'bg-status-success-text' },
  ANNUAL_LEAVE_ADJUST: { label: '調整特休', color: 'bg-status-info-text' },
  ANNUAL_LEAVE_BATCH_AUTO_CALC: { label: '批次計算特休', color: 'bg-status-neutral-text' },
  ANNUAL_LEAVE_EXPIRY_RECOMPUTE: { label: '特休到期重算', color: 'bg-status-neutral-text' },
  // 動物 — 延伸事件
  ANIMAL_ASSIGN: { label: '分配動物', color: 'bg-status-purple-text' },
  ANIMAL_REMARK_UPDATE: { label: '更新動物備註', color: 'bg-status-info-text' },
  ANIMAL_IMPORT: { label: '匯入動物', color: 'bg-status-success-text' },
  IACUC_CHANGE: { label: 'IACUC 變更', color: 'bg-status-info-text' },
  WEIGHT_SOFT_DELETE: { label: '刪除體重', color: 'bg-status-error-text' },
  WEIGHT_IMPORT: { label: '匯入體重', color: 'bg-status-success-text' },
  SUDDEN_DEATH: { label: '猝死記錄', color: 'bg-audit-sacrifice' },
  BLOOD_TEST_ITEM_CORRECT: { label: '血檢項目更正', color: 'bg-status-warning-text' },
  PRESET_CREATE: { label: '建立血檢預設', color: 'bg-status-success-text' },
  PRESET_UPDATE: { label: '更新血檢預設', color: 'bg-status-info-text' },
  PRESET_DELETE: { label: '刪除血檢預設', color: 'bg-status-error-text' },
  CARE_RECORD_CREATE: { label: '建立照護紀錄', color: 'bg-status-success-text' },
  CARE_RECORD_UPDATE: { label: '更新照護紀錄', color: 'bg-status-info-text' },
  CARE_RECORD_DELETE: { label: '刪除照護紀錄', color: 'bg-status-error-text' },
  VET_ADVICE_RECORD_CREATE: { label: '建立獸醫建議', color: 'bg-audit-medical' },
  VET_ADVICE_RECORD_UPDATE: { label: '更新獸醫建議', color: 'bg-audit-medical' },
  VET_ADVICE_RECORD_DELETE: { label: '刪除獸醫建議', color: 'bg-status-error-text' },
  VET_PATROL_REPORT_CREATED: { label: '建立巡場報告', color: 'bg-audit-medical' },
  VET_PATROL_REPORT_UPDATED: { label: '更新巡場報告', color: 'bg-audit-medical' },
  VET_PATROL_REPORT_SUBMITTED_FOR_FOLLOWUP: { label: '巡場報告送追蹤', color: 'bg-status-warning-text' },
  VET_PATROL_REPORT_ACKNOWLEDGED: { label: '巡場報告已確認', color: 'bg-status-purple-text' },
  VET_PATROL_REPORT_COMPLETED: { label: '巡場報告完成', color: 'bg-status-success-text' },
  VET_PATROL_REPORT_DISCARDED: { label: '巡場報告作廢', color: 'bg-status-neutral-text' },
  VET_PATROL_REPORT_DELETED: { label: '刪除巡場報告', color: 'bg-status-error-text' },
  VET_PATROL_ENTRY_PHOTO_DELETED: { label: '刪除巡場照片', color: 'bg-status-error-text' },
  BYPRODUCT_SAMPLE_CREATE: { label: '建立副產物樣本', color: 'bg-status-success-text' },
  BYPRODUCT_SAMPLE_UPDATE: { label: '更新副產物樣本', color: 'bg-status-info-text' },
  BYPRODUCT_SAMPLE_DELETE: { label: '刪除副產物樣本', color: 'bg-status-error-text' },
  ANIMAL_SOURCE_CREATE: { label: '建立動物來源', color: 'bg-status-success-text' },
  ANIMAL_SOURCE_UPDATE: { label: '更新動物來源', color: 'bg-status-info-text' },
  ANIMAL_SOURCE_DEACTIVATE: { label: '停用動物來源', color: 'bg-status-neutral-text' },
  // 動物 — 轉移流程
  TRANSFER_INITIATE: { label: '發起動物轉移', color: 'bg-status-info-text' },
  TRANSFER_VET_EVALUATE: { label: '獸醫評估轉移', color: 'bg-audit-medical' },
  TRANSFER_ASSIGN_PLAN: { label: '指派轉移計畫', color: 'bg-status-info-text' },
  TRANSFER_APPROVE: { label: '核准動物轉移', color: 'bg-status-purple-text' },
  TRANSFER_COMPLETE: { label: '完成動物轉移', color: 'bg-status-success-text' },
  TRANSFER_REJECT: { label: '駁回動物轉移', color: 'bg-status-error-text' },
  // 醫療匯出
  EXPORT_MEDICAL: { label: '匯出醫療資料', color: 'bg-audit-medical' },
  EXPORT_SURGERY: { label: '匯出手術資料', color: 'bg-audit-medical' },
  EXPORT_BLOOD_TEST: { label: '匯出血檢資料', color: 'bg-audit-medical' },
  ANIMAL_MEDICAL_WEEKLY_REPORT_READ: { label: '讀取醫療週報', color: 'bg-audit-medical' },
  // ERP — 延伸事件
  DOC_WM_APPROVE: { label: '倉管核准單據', color: 'bg-status-purple-text' },
  DOC_ADMIN_APPROVE: { label: '主管核准單據', color: 'bg-status-purple-text' },
  DOC_ADMIN_REJECT: { label: '主管駁回單據', color: 'bg-status-error-text' },
  PRODUCT_CREATE_WITH_SKU: { label: '建立產品（含 SKU）', color: 'bg-status-success-text' },
  PRODUCT_STATUS_CHANGE: { label: '產品狀態變更', color: 'bg-status-info-text' },
  PRODUCT_HARD_DELETE: { label: '永久刪除產品', color: 'bg-status-error-text' },
  PRODUCT_CATEGORY_CREATE: { label: '建立產品分類', color: 'bg-status-success-text' },
  PRODUCT_IMPORT: { label: '匯入產品', color: 'bg-status-success-text' },
  PARTNER_IMPORT: { label: '匯入夥伴', color: 'bg-status-success-text' },
  WAREHOUSE_IMPORT: { label: '匯入倉庫', color: 'bg-status-success-text' },
  SKU_CATEGORY_UPDATE: { label: '更新 SKU 分類', color: 'bg-status-info-text' },
  SKU_CATEGORY_DELETE: { label: '刪除 SKU 分類', color: 'bg-status-error-text' },
  SKU_SUBCATEGORY_CREATE: { label: '建立 SKU 子分類', color: 'bg-status-success-text' },
  SKU_SUBCATEGORY_UPDATE: { label: '更新 SKU 子分類', color: 'bg-status-info-text' },
  SKU_SUBCATEGORY_DELETE: { label: '刪除 SKU 子分類', color: 'bg-status-error-text' },
  STORAGE_INVENTORY_UPDATE: { label: '調整庫存', color: 'bg-status-info-text' },
  AP_PAYMENT_CREATED: { label: '建立應付付款', color: 'bg-status-success-text' },
  AR_RECEIPT_CREATED: { label: '建立應收收款', color: 'bg-status-success-text' },
  DATA_EXPORT: { label: '匯出資料', color: 'bg-audit-data' },
  DATA_IMPORT: { label: '匯入資料', color: 'bg-audit-data' },
  // 設施 / 設備
  MAINTENANCE_CREATE: { label: '建立維護紀錄', color: 'bg-status-success-text' },
  MAINTENANCE_UPDATE: { label: '更新維護紀錄', color: 'bg-status-info-text' },
  MAINTENANCE_DELETE: { label: '刪除維護紀錄', color: 'bg-status-error-text' },
  MAINTENANCE_REVIEWER_SIGNATURE: { label: '維護覆核簽章', color: 'bg-status-purple-text' },
  DISPOSAL_APPLICANT_SIGNATURE: { label: '報廢申請簽章', color: 'bg-status-warning-text' },
  DISPOSAL_APPROVER_SIGNATURE: { label: '報廢核准簽章', color: 'bg-status-purple-text' },
  DISPOSAL_RESTORE: { label: '取消設備報廢', color: 'bg-status-neutral-text' },
  EQUIPMENT_AUTO_RESTORE: { label: '設備自動復原', color: 'bg-status-neutral-text' },
  FACILITY_SPECIES_CREATE: { label: '建立物種', color: 'bg-status-success-text' },
  FACILITY_SPECIES_UPDATE: { label: '更新物種', color: 'bg-status-info-text' },
  FACILITY_SPECIES_DELETE: { label: '刪除物種', color: 'bg-status-error-text' },
  FACILITY_FACILITY_CREATE: { label: '建立場所', color: 'bg-status-success-text' },
  FACILITY_FACILITY_UPDATE: { label: '更新場所', color: 'bg-status-info-text' },
  FACILITY_FACILITY_DELETE: { label: '刪除場所', color: 'bg-status-error-text' },
  FACILITY_BUILDING_CREATE: { label: '建立建物', color: 'bg-status-success-text' },
  FACILITY_BUILDING_UPDATE: { label: '更新建物', color: 'bg-status-info-text' },
  FACILITY_BUILDING_DELETE: { label: '刪除建物', color: 'bg-status-error-text' },
  FACILITY_ZONE_CREATE: { label: '建立區域', color: 'bg-status-success-text' },
  FACILITY_ZONE_UPDATE: { label: '更新區域', color: 'bg-status-info-text' },
  FACILITY_ZONE_DELETE: { label: '刪除區域', color: 'bg-status-error-text' },
  FACILITY_PEN_CREATE: { label: '建立欄位', color: 'bg-status-success-text' },
  FACILITY_PEN_BATCH_CREATE: { label: '批次建立欄位', color: 'bg-status-success-text' },
  FACILITY_PEN_UPDATE: { label: '更新欄位', color: 'bg-status-info-text' },
  FACILITY_PEN_DELETE: { label: '刪除欄位', color: 'bg-status-error-text' },
  FACILITY_DEPARTMENT_CREATE: { label: '建立部門', color: 'bg-status-success-text' },
  FACILITY_DEPARTMENT_UPDATE: { label: '更新部門', color: 'bg-status-info-text' },
  FACILITY_DEPARTMENT_DELETE: { label: '刪除部門', color: 'bg-status-error-text' },
  // 站內信
  MESSAGE_THREAD_CREATED: { label: '建立訊息主旨', color: 'bg-status-success-text' },
  MESSAGE_SENT: { label: '傳送訊息', color: 'bg-status-info-text' },
  MESSAGE_DELETED: { label: '刪除訊息', color: 'bg-status-error-text' },
  // 通用動詞（GLP 各模組共用）
  CREATE: { label: '建立', color: 'bg-status-success-text' },
  UPDATE: { label: '更新', color: 'bg-status-info-text' },
  DELETE: { label: '刪除', color: 'bg-status-error-text' },
  APPROVE: { label: '核准', color: 'bg-status-purple-text' },
  ACKNOWLEDGE: { label: '確認', color: 'bg-status-info-text' },
  // 補全：user_activity_logs 實際出現但先前缺映射（操作日誌會露原始 event_type）
  ACCOUNT_LOCKOUT: { label: '帳號鎖定', color: 'bg-status-error-text' },
  PERMISSION_DENIED: { label: '權限不足遭拒', color: 'bg-status-error-text' },
  RATE_LIMIT_API: { label: 'API 頻率限制', color: 'bg-status-warning-text' },
  USER_AUTO_SUSPENDED: { label: '使用者自動停權', color: 'bg-status-warning-text' },
  DOC_HARD_DELETE: { label: '永久刪除單據', color: 'bg-status-error-text' },
  MAINTENANCE_REVIEW: { label: '維護覆核', color: 'bg-status-info-text' },
  MAINTENANCE_REVIEW_APPROVE: { label: '維護覆核核准', color: 'bg-status-purple-text' },
  ANIMAL_RESERVED: { label: '預約動物', color: 'bg-status-purple-text' },
  PLANNED_EXPERIMENT_CREATED: { label: '建立試驗規劃', color: 'bg-status-success-text' },
  APPLICATION_NOTICE_CREATED: { label: '建立計畫須知', color: 'bg-status-success-text' },
  APPLICATION_NOTICE_CONTENT_UPDATED: { label: '更新計畫須知內容', color: 'bg-status-info-text' },
  APPLICATION_NOTICE_ACTIVATED: { label: '啟用計畫須知', color: 'bg-status-purple-text' },
  PROTOCOL_COEDITOR_ASSIGN: { label: '指派協作編輯', color: 'bg-audit-protocol' },
  PROTOCOL_VET_ASSIGN: { label: '指派獸醫', color: 'bg-audit-protocol' },
  PROTOCOL_IMPORT_DELETED: { label: '刪除匯入計畫書', color: 'bg-status-error-text' },
  PROTOCOL_TEMPLATE_VERSION_CREATED: { label: '建立計畫書範本版本', color: 'bg-status-success-text' },
  PROTOCOL_TEMPLATE_VERSION_DELETED: { label: '刪除計畫書範本版本', color: 'bg-status-error-text' },
  PROTOCOL_TEMPLATE_VERSION_SET_CURRENT: { label: '設為現行計畫書範本版本', color: 'bg-status-purple-text' },
  VET_PATROL_REPORT_SUBMITTED: { label: '送出巡場報告', color: 'bg-status-warning-text' },
}

// 資料類型對應中文（與 UI 上「資料類型」一致；避免 vet/QAU 看到 raw 表名）
//
// 涵蓋來源：backend 全 codebase `AuditEntity::new("...")` 字面值掃描（Gemini PR #412
// review 補完後）。新增 entity_type 時，後端 author 應同步 PR 此檔，未補映射時
// fallback 顯示原值（UI 不會白屏，但會露出 raw 表名）。
export const entityTypeLabels: Record<string, string> = {
  // 既有 ERP / Animal / Protocol entity 對應
  document: '單據',
  partner: '夥伴',
  partner_import_job: '夥伴匯入批次',
  product: '產品',
  product_category: '產品分類',
  warehouse: '倉庫',
  role: '角色',
  user: '使用者',
  session: '登入工作階段',
  database: '資料庫',
  ai_api_key: 'AI API 金鑰',
  system_setting: '系統設定',
  // 動物相關
  animal: '動物',
  animal_observation: '觀察記錄',
  animal_surgery: '手術記錄',
  animal_surgeries: '手術記錄',
  animal_weight: '體重記錄',
  animal_vaccination: '疫苗記錄',
  animal_sacrifice: '犧牲記錄',
  animal_sudden_deaths: '猝死記錄',
  animal_pathology: '病理報告',
  animal_blood_test: '血液檢查',
  animal_blood_test_item: '血檢項目',
  animal_source: '動物來源',
  animal_transfers: '動物轉移',
  animal_import_batch: '動物匯入批次',
  blood_test_template: '血檢模板',
  blood_test_panel: '血檢組合',
  blood_test_preset: '血檢預設',
  care_medication_record: '日常用藥紀錄',
  vet_recommendation: '獸醫建議',
  vet_patrol_reports: '巡場報告',
  euthanasia: '安樂死',
  // 計畫書 / 修正案
  protocol: '計畫書',
  amendment: '計畫修正案',
  // 設施 / 設備
  facility: '設施',
  equipment: '設備',
  maintenance_record: '維護紀錄',
  // HR
  overtime_record: '加班紀錄',
  leave_request: '請假申請',
  attendance_record: '出勤紀錄',
  // 站內信
  message_threads: '站內信',
  messages: '訊息',
  // QA / GLP（Gemini PR #412 review：補完整 table 名稱對應，避免縮寫漏失）
  qa_inspections: '稽查報告',
  qa_inspection: '稽查報告',
  qa_non_conformances: '品質異常 (NC)',
  qa_nc: '品質異常 (NC)',
  qa_sop_documents: 'SOP 文件',
  qa_sop: 'SOP 文件',
  qa_schedules: '稽查排程',
  qa_schedule: '稽查排程',
  qa_schedule_items: '稽查排程項目',
  // 後端有時送複數型（plural）— 加 alias 避免白屏
  protocols: '計畫書',
  animals: '動物',
  facilities: '設施',
  users: '使用者',
  // 補全：user_activity_logs 實際出現但先前缺映射（QAU 稽核摘要會露原始 code）
  annual_leave_entitlement: '特休額度',
  application_notice: '計畫須知',
  electronic_signature: '電子簽章',
  planned_experiment: '試驗規劃',
  protocol_template_version: '計畫書範本版本',
  pi_account_invite: '主持人帳號邀請',
  // 補全：後端 AuditEntity::new 有、先前缺映射（操作日誌／稽核檢視會露原始 code）
  // 設施
  species: '物種',
  building: '棟別',
  zone: '區域',
  pen: '欄位',
  department: '部門',
  // 設備 / 會計 / 廢棄物再利用
  equipment_disposals: '設備報廢',
  ap_payment: '應付付款',
  ar_receipt: '應收收款',
  byproduct_sample: '副產物樣本',
  // 動物（獸醫建議另一 code）
  animal_vet_advice: '獸醫建議',
  // GLP 合規
  reference_standard: '對照標準品',
  document_revision: '文件修訂',
  risk_entry: '風險項目',
  change_request: '變更申請',
  monitoring_point: '監控點',
  environment_reading: '環境監測讀值',
  competency_assessment: '能力評鑑',
  training_requirement: '訓練需求',
  formulation_record: '配製紀錄',
  // 安全
  ip_blocklist: 'IP 封鎖',
}

// 事件類別 → 可選資料類型 配對
export const categoryEntityMap: Record<string, { value: string; label: string }[]> = {
  all: [
    { value: 'document', label: '單據' },
    { value: 'product', label: '產品' },
    { value: 'warehouse', label: '倉庫' },
    { value: 'partner', label: '夥伴' },
    { value: 'blood_test_template', label: '血檢模板' },
    { value: 'blood_test_panel', label: '血檢組合' },
    { value: 'animal', label: '動物' },
    { value: 'animal_observation', label: '觀察記錄' },
    { value: 'animal_surgery', label: '手術記錄' },
    { value: 'animal_weight', label: '體重記錄' },
    { value: 'animal_vaccination', label: '疫苗記錄' },
    { value: 'animal_sacrifice', label: '犧牲記錄' },
    { value: 'animal_pathology', label: '病理報告' },
    { value: 'animal_blood_test', label: '血液檢查' },
    { value: 'vet_recommendation', label: '獸醫建議' },
    { value: 'protocol', label: '計畫書' },
    { value: 'role', label: '角色' },
  ],
  ERP: [
    { value: 'document', label: '單據' },
    { value: 'product', label: '產品' },
    { value: 'warehouse', label: '倉庫' },
    { value: 'partner', label: '夥伴' },
    { value: 'blood_test_template', label: '血檢模板' },
    { value: 'blood_test_panel', label: '血檢組合' },
  ],
  AUP: [
    { value: 'protocol', label: '計畫書' },
  ],
  ANIMAL: [
    { value: 'animal', label: '動物' },
    { value: 'animal_observation', label: '觀察記錄' },
    { value: 'animal_surgery', label: '手術記錄' },
    { value: 'animal_weight', label: '體重記錄' },
    { value: 'animal_vaccination', label: '疫苗記錄' },
    { value: 'animal_sacrifice', label: '犧牲記錄' },
    { value: 'animal_pathology', label: '病理報告' },
    { value: 'animal_blood_test', label: '血液檢查' },
    { value: 'vet_recommendation', label: '獸醫建議' },
  ],
}

// 安全稽核警示類型 → 中文（security_alerts.alert_type）
export const alertTypeLabels: Record<string, string> = {
  CSP_VIOLATION: 'CSP 違規',
  CSP_VIOLATION_REPORT_ONLY: 'CSP 違規（僅回報）',
  REFRESH_TOKEN_REUSE: 'Refresh Token 重用',
  brute_force: '暴力破解嘗試',
  idor_probe: 'IDOR 探測',
  unusual_login: '異常登入',
}

// 警示嚴重度 → 中文（security_alerts.severity）
export const severityLabels: Record<string, string> = {
  critical: '嚴重',
  high: '高',
  warning: '警告',
  medium: '中',
  info: '資訊',
  low: '低',
}
