//! OpenAPI 文件入口 — Phase 1+2A+2B：Auth、Users、Roles、Facility、Warehouse、Protocol、電子簽章、動物管理
//!
//! 使用 utoipa 產生 Swagger/OpenAPI 3.0 規格。
//! 掛載 SwaggerUI 後可在 `/swagger-ui` 瀏覽互動式 API 文件。

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "豬博士 iPig 系統 API",
        version = "2.0.0",
        description = "\
豬博士 iPig 系統後端 API（GLP 合規之整合型實驗動物管理平台）。\n\n\
**AI Agent 整合**：\n\
- A2A Agent Card：`/.well-known/agent.json`\n\
- MCP Discovery：`/.well-known/mcp.json`，端點 `/api/v1/mcp`（JSON-RPC 2.0）\n\
- WebMCP Manifest：`/.well-known/webmcp.json`\n\
- LLM 友善說明：`/llms.txt`\n\n\
**認證**：\n\
- Web Session：經 `/api/v1/auth/login` 取得 HttpOnly Cookie JWT，可選 TOTP 2FA\n\
- MCP API Key：Bearer token，前綴 `mcp_`，由系統管理員於 `user_mcp_keys` 發放\n\
- AI API Key：Bearer token，前綴 `ai_`，僅可呼叫 `/api/v1/ai`\n\n\
**速率限制**：每 IP 每分鐘 60 請求，burst 20（由 nginx 與 Cloudflare WAF 雙層防護）。\n\n\
**回應格式**：所有錯誤統一為 `AppError`，回傳 JSON `{ \"error\": { \"code\": ..., \"message\": ... } }`。",
        contact(name = "豬博士 iPig 系統團隊", url = "https://ipigsystem.asia/")
    ),
    paths(
        // === 監控 ===
        crate::handlers::health::health_check,
        crate::handlers::metrics::metrics_handler,
        crate::handlers::metrics::vitals_handler,
        // === 認證 ===
        crate::handlers::auth::login,
        crate::handlers::auth::refresh_token,
        crate::handlers::auth::logout,
        crate::handlers::auth::me,
        crate::handlers::auth::update_me,
        crate::handlers::auth::change_own_password,
        crate::handlers::auth::confirm_password,
        crate::handlers::auth::forgot_password,
        crate::handlers::auth::reset_password_with_token,
        crate::handlers::auth::heartbeat,
        crate::handlers::auth::stop_impersonate,
        crate::handlers::auth::export_me,
        crate::handlers::auth::delete_me_account,
        crate::handlers::two_factor::setup_2fa,
        crate::handlers::two_factor::confirm_2fa_setup,
        crate::handlers::two_factor::disable_2fa,
        crate::handlers::two_factor::verify_2fa_login,
        crate::handlers::user_preferences::get_all_preferences,
        crate::handlers::user_preferences::get_preference,
        crate::handlers::user_preferences::upsert_preference,
        crate::handlers::user_preferences::delete_preference,
        // === 使用者管理 ===
        crate::handlers::user::create_user,
        crate::handlers::user::list_users,
        crate::handlers::user::get_user,
        crate::handlers::user::update_user,
        crate::handlers::user::delete_user,
        crate::handlers::user::reset_user_password,
        crate::handlers::user::impersonate_user,
        // === 角色權限 ===
        crate::handlers::role::create_role,
        crate::handlers::role::list_roles,
        crate::handlers::role::get_role,
        crate::handlers::role::update_role,
        crate::handlers::role::delete_role,
        crate::handlers::role::list_permissions,
        // === 設施管理 ===
        crate::handlers::facility::list_species,
        crate::handlers::facility::get_species,
        crate::handlers::facility::create_species,
        crate::handlers::facility::update_species,
        crate::handlers::facility::delete_species,
        crate::handlers::facility::list_facilities,
        crate::handlers::facility::get_facility,
        crate::handlers::facility::create_facility,
        crate::handlers::facility::update_facility,
        crate::handlers::facility::delete_facility,
        crate::handlers::facility::list_buildings,
        crate::handlers::facility::get_building,
        crate::handlers::facility::create_building,
        crate::handlers::facility::update_building,
        crate::handlers::facility::delete_building,
        crate::handlers::facility::list_zones,
        crate::handlers::facility::get_zone,
        crate::handlers::facility::create_zone,
        crate::handlers::facility::update_zone,
        crate::handlers::facility::delete_zone,
        crate::handlers::facility::list_pens,
        crate::handlers::facility::get_pen,
        crate::handlers::facility::create_pen,
        crate::handlers::facility::update_pen,
        crate::handlers::facility::delete_pen,
        crate::handlers::facility::list_departments,
        crate::handlers::facility::get_department,
        crate::handlers::facility::create_department,
        crate::handlers::facility::update_department,
        crate::handlers::facility::delete_department,
        // === 倉儲管理 ===
        crate::handlers::warehouse::create_warehouse,
        crate::handlers::warehouse::list_warehouses,
        crate::handlers::warehouse::list_warehouses_with_shelves,
        crate::handlers::warehouse::get_warehouse,
        crate::handlers::warehouse::update_warehouse,
        crate::handlers::warehouse::delete_warehouse,
        crate::handlers::storage_location::create_storage_location,
        crate::handlers::storage_location::list_storage_locations,
        crate::handlers::storage_location::get_storage_location,
        crate::handlers::storage_location::update_storage_location,
        crate::handlers::storage_location::delete_storage_location,
        crate::handlers::storage_location::update_warehouse_layout,
        crate::handlers::storage_location::generate_storage_location_code,
        crate::handlers::storage_location::get_storage_location_inventory,
        crate::handlers::storage_location::create_storage_location_inventory_item,
        crate::handlers::storage_location::update_storage_location_inventory_item,
        crate::handlers::sku::get_sku_categories,
        crate::handlers::sku::get_sku_categories_tree,
        crate::handlers::sku::get_sku_subcategories,
        crate::handlers::sku::create_sku_subcategory,
        crate::handlers::sku::update_sku_category,
        crate::handlers::sku::delete_sku_category,
        crate::handlers::sku::update_sku_subcategory,
        crate::handlers::sku::delete_sku_subcategory,
        crate::handlers::sku::generate_sku,
        crate::handlers::sku::validate_sku,
        crate::handlers::sku::preview_sku,
        crate::handlers::sku::create_product_with_sku,
        // === 計畫書管理 ===
        crate::handlers::protocol::crud::create_protocol,
        crate::handlers::protocol::crud::list_protocols,
        crate::handlers::protocol::crud::get_protocol,
        crate::handlers::protocol::crud::update_protocol,
        crate::handlers::protocol::crud::submit_protocol,
        crate::handlers::protocol::crud::change_protocol_status,
        crate::handlers::protocol::crud::get_protocol_versions,
        crate::handlers::protocol::crud::get_protocol_activities,
        crate::handlers::protocol::crud::get_my_protocols,
        crate::handlers::protocol::crud::get_protocol_animal_stats,
        crate::handlers::protocol::crud::save_vet_review_form,
        // R32-A8d: legacy v1 export_protocol_pdf 已刪除（前端走 v2 / v3）
        // R32-A8b: surgery v3 docx export（animal mod 私有，走頂層 re-export）
        crate::handlers::export_surgery_pdf_v3,
        // === 審查管理 ===
        crate::handlers::protocol::review::assign_reviewer,
        crate::handlers::protocol::review::list_review_assignments,
        crate::handlers::protocol::review::create_review_comment,
        crate::handlers::protocol::review::list_review_comments,
        crate::handlers::protocol::review::resolve_review_comment,
        crate::handlers::protocol::review::reply_review_comment,
        crate::handlers::protocol::review::save_reply_draft,
        crate::handlers::protocol::review::get_reply_draft,
        crate::handlers::protocol::review::submit_reply_from_draft,
        // === 電子簽章 (GLP) ===
        crate::handlers::sign_sacrifice_record,
        crate::handlers::get_sacrifice_signature_status,
        crate::handlers::sign_observation_record,
        crate::handlers::sign_euthanasia_order,
        crate::handlers::get_euthanasia_signature_status,
        crate::handlers::sign_transfer_record,
        crate::handlers::get_transfer_signature_status,
        crate::handlers::sign_protocol_review,
        crate::handlers::get_protocol_signature_status,
        crate::handlers::invalidate_signature,
        crate::handlers::add_record_annotation,
        crate::handlers::get_record_annotations,
        // === 動物管理 ===
        crate::handlers::list_animals,
        crate::handlers::get_animal_stats,
        crate::handlers::list_animals_by_pen,
        crate::handlers::get_animal,
        crate::handlers::create_animal,
        crate::handlers::update_animal,
        crate::handlers::delete_animal,
        crate::handlers::batch_assign_animals,
        crate::handlers::mark_animal_vet_read,
        crate::handlers::get_animal_events,
        // === 動物子模組 ===
        crate::handlers::list_animal_observations,
        crate::handlers::get_animal_observation,
        crate::handlers::create_animal_observation,
        crate::handlers::update_animal_observation,
        crate::handlers::delete_animal_observation,
        crate::handlers::list_animal_surgeries,
        crate::handlers::get_animal_surgery,
        crate::handlers::create_animal_surgery,
        crate::handlers::update_animal_surgery,
        crate::handlers::delete_animal_surgery,
        crate::handlers::list_animal_weights,
        crate::handlers::create_animal_weight,
        crate::handlers::update_animal_weight,
        crate::handlers::delete_animal_weight,
        crate::handlers::list_animal_vaccinations,
        crate::handlers::create_animal_vaccination,
        crate::handlers::update_animal_vaccination,
        crate::handlers::delete_animal_vaccination,
        crate::handlers::get_animal_sacrifice,
        crate::handlers::upsert_animal_sacrifice,
        crate::handlers::get_animal_pathology_report,
        crate::handlers::upsert_animal_pathology_report,
        crate::handlers::list_animal_transfers,
        crate::handlers::get_transfer,
        crate::handlers::initiate_transfer,
        crate::handlers::approve_transfer,
        crate::handlers::complete_transfer,
        crate::handlers::reject_transfer,
        // === HR / 通知 / 稽核 ===
        crate::handlers::list_attendance,
        crate::handlers::clock_in,
        crate::handlers::list_leaves,
        crate::handlers::create_leave,
        crate::handlers::list_overtime,
        crate::handlers::create_overtime,
        crate::handlers::list_notifications,
        crate::handlers::get_unread_count,
        crate::handlers::list_activity_logs,
        crate::handlers::list_login_events,
        crate::handlers::get_audit_dashboard,
        // === 產品管理 ===
        crate::handlers::create_product,
        crate::handlers::list_products,
        crate::handlers::get_product,
        crate::handlers::update_product,
        crate::handlers::delete_product,
        crate::handlers::list_categories,
        crate::handlers::create_category,
        crate::handlers::import_products,
        crate::handlers::preview_product_import,
        crate::handlers::download_product_import_template,
        crate::handlers::create_product_with_sku,
        // === SKU ===
        crate::handlers::get_sku_categories,
        crate::handlers::get_sku_subcategories,
        crate::handlers::generate_sku,
        crate::handlers::validate_sku,
        crate::handlers::preview_sku,
        // === 合作夥伴管理 ===
        crate::handlers::create_partner,
        crate::handlers::list_partners,
        crate::handlers::get_partner,
        crate::handlers::update_partner,
        crate::handlers::delete_partner,
        crate::handlers::generate_partner_code,
        crate::handlers::import_partners,
        crate::handlers::download_partner_import_template,
        // === 單據管理 ===
        crate::handlers::create_document,
        crate::handlers::list_documents,
        crate::handlers::get_document,
        crate::handlers::update_document,
        crate::handlers::delete_document,
        crate::handlers::submit_document,
        crate::handlers::approve_document,
        crate::handlers::cancel_document,
        // === 報表 ===
        crate::handlers::get_stock_on_hand_report,
        crate::handlers::get_stock_ledger_report,
        crate::handlers::get_purchase_lines_report,
        crate::handlers::get_sales_lines_report,
        crate::handlers::get_cost_summary_report,
        crate::handlers::get_blood_test_cost_report,
        crate::handlers::get_blood_test_analysis,
        // === 會計 ===
        crate::handlers::get_chart_of_accounts,
        crate::handlers::get_trial_balance,
        crate::handlers::get_journal_entries,
        crate::handlers::get_ap_aging,
        crate::handlers::get_ar_aging,
        crate::handlers::create_ap_payment,
        crate::handlers::create_ar_receipt,
        // === 治療藥物 ===
        crate::handlers::treatment_drug::list_treatment_drugs,
        crate::handlers::treatment_drug::admin_list_treatment_drugs,
        crate::handlers::treatment_drug::create_treatment_drug,
        crate::handlers::treatment_drug::update_treatment_drug,
        crate::handlers::treatment_drug::delete_treatment_drug,
        crate::handlers::treatment_drug::import_treatment_drugs_from_erp,
    ),
    components(
        schemas(
            // 監控
            crate::handlers::health::HealthResponse,
            crate::handlers::health::HealthChecks,
            crate::handlers::health::ComponentCheck,
            // M14: PoolCheck 已移除（不再對外暴露 DB pool 細節）
            crate::handlers::health::DiskCheck,
            crate::handlers::metrics::WebVitalsMetric,
            // 共用
            crate::error::ErrorResponse,
            crate::error::ErrorDetail,
            // User models
            crate::models::LoginRequest,
            crate::models::LoginResponse,
            crate::models::RefreshTokenRequest,
            crate::models::UserResponse,
            crate::models::CreateUserRequest,
            crate::models::UpdateUserRequest,
            crate::models::ChangeOwnPasswordRequest,
            crate::models::ConfirmPasswordRequest,
            crate::models::ResetPasswordRequest,
            crate::models::ForgotPasswordRequest,
            crate::models::ResetPasswordWithTokenRequest,
            crate::models::user_preferences::AllPreferencesResponse,
            crate::models::user_preferences::PreferenceResponse,
            crate::models::user_preferences::UpsertPreferenceRequest,
            crate::models::TwoFactorSetupResponse,
            crate::models::TwoFactorConfirmRequest,
            crate::models::TwoFactorDisableRequest,
            crate::models::TwoFactorLoginRequest,
            crate::models::ThemePreference,
            crate::models::LanguagePreference,
            crate::models::UserTraining,
            // Role models
            crate::models::CreateRoleRequest,
            crate::models::UpdateRoleRequest,
            crate::models::RoleWithPermissions,
            crate::models::Permission,
            // Facility models
            crate::models::Species,
            crate::models::SpeciesListItem,
            crate::models::SpeciesListQuery,
            crate::models::CreateSpeciesRequest,
            crate::models::UpdateSpeciesRequest,
            crate::models::Facility,
            crate::models::CreateFacilityRequest,
            crate::models::UpdateFacilityRequest,
            crate::models::Building,
            crate::models::BuildingWithFacility,
            crate::models::CreateBuildingRequest,
            crate::models::UpdateBuildingRequest,
            crate::models::Zone,
            crate::models::ZoneWithBuilding,
            crate::models::CreateZoneRequest,
            crate::models::UpdateZoneRequest,
            crate::models::Pen,
            crate::models::PenDetails,
            crate::models::CreatePenRequest,
            crate::models::UpdatePenRequest,
            crate::models::Department,
            crate::models::DepartmentWithManager,
            crate::models::CreateDepartmentRequest,
            crate::models::UpdateDepartmentRequest,
            // Warehouse models
            crate::models::Warehouse,
            crate::models::CreateWarehouseRequest,
            crate::models::UpdateWarehouseRequest,
            crate::models::StorageLocation,
            crate::models::StorageLocationWithWarehouse,
            crate::models::CreateStorageLocationRequest,
            crate::models::UpdateStorageLocationRequest,
            crate::models::UpdateStorageLayoutRequest,
            crate::models::StorageLayoutItem,
            crate::models::StorageLocationQuery,
            crate::models::StorageLocationInventoryItem,
            crate::models::CreateStorageLocationInventoryItemRequest,
            crate::models::UpdateStorageLocationInventoryItemRequest,
            crate::models::CategoriesResponse,
            crate::models::CategoriesTreeResponse,
            crate::models::CategoryForEdit,
            crate::models::SubcategoryForEdit,
            crate::models::CreateSkuSubcategoryRequest,
            crate::models::UpdateSkuCategoryRequest,
            crate::models::UpdateSkuSubcategoryRequest,
            crate::models::SubcategoriesResponse,
            crate::models::GenerateSkuRequest,
            crate::models::GenerateSkuResponse,
            crate::models::ValidateSkuRequest,
            crate::models::ValidateSkuResponse,
            crate::models::SkuPreviewRequest,
            crate::models::SkuPreviewResponse,
            crate::models::CreateProductWithSkuRequest,
            crate::models::ProductWithUom,
            crate::models::Product,
            crate::models::ProductUomConversion,
            // Protocol models
            crate::models::Protocol,
            crate::models::ProtocolStatus,
            crate::models::ProtocolVersion,
            crate::models::ProtocolActivityType,
            crate::models::ProtocolActivity,
            crate::models::ProtocolActivityResponse,
            crate::models::ProtocolRole,
            crate::models::UserProtocol,
            crate::models::ReviewAssignment,
            crate::models::ReviewComment,
            crate::models::ProtocolAttachment,
            crate::models::VetReviewAssignment,
            crate::models::VetReviewItem,
            crate::models::VetReviewForm,
            crate::models::SystemSetting,
            crate::models::CreateProtocolRequest,
            crate::models::UpdateProtocolRequest,
            crate::models::ChangeStatusRequest,
            crate::models::AssignReviewerRequest,
            crate::models::CreateCommentRequest,
            crate::models::ReplyCommentRequest,
            crate::models::SaveDraftRequest,
            crate::models::SubmitReplyRequest,
            crate::models::SaveVetReviewFormRequest,
            crate::models::ProtocolResponse,
            crate::models::ProtocolListItem,
            crate::models::ReviewCommentResponse,
            crate::models::ReviewAssignmentResponse,
            // 電子簽章（經 handlers 再匯出）
            crate::handlers::PreferenceExport,
            crate::handlers::GdprExportResponse,
            crate::handlers::SignRecordRequest,
            crate::handlers::SignRecordResponse,
            crate::handlers::CreateAnnotationRequest,
            crate::handlers::AnnotationResponse,
            crate::handlers::SignatureStatusResponse,
            crate::handlers::SignatureInfo,
            crate::handlers::InvalidateSignatureRequest,
            crate::handlers::InvalidateSignatureResponse,
            // 動物管理
            crate::models::Animal,
            crate::models::AnimalListItem,
            crate::models::AnimalQuery,
            crate::models::CreateAnimalRequest,
            crate::models::UpdateAnimalRequest,
            crate::models::AnimalsByPen,
            crate::models::AnimalStatsResponse,
            crate::models::BatchAssignRequest,
            crate::models::DeleteRequest,
            crate::models::AnimalStatus,
            crate::models::AnimalBreed,
            crate::models::AnimalGender,
            crate::handlers::AnimalEvent,
            // 動物子模組
            crate::models::AnimalObservation,
            crate::models::AnimalSurgery,
            crate::models::AnimalWeight,
            crate::models::AnimalWeightResponse,
            crate::models::AnimalVaccination,
            crate::models::AnimalSacrifice,
            crate::models::AnimalTransfer,
            crate::models::AnimalPathologyReport,
            crate::models::TransferVetEvaluation,
            crate::models::RecordFilterQuery,
            crate::models::CreateObservationRequest,
            crate::models::UpdateObservationRequest,
            crate::models::CreateSurgeryRequest,
            crate::models::UpdateSurgeryRequest,
            crate::models::CreateWeightRequest,
            crate::models::UpdateWeightRequest,
            crate::models::CreateVaccinationRequest,
            crate::models::UpdateVaccinationRequest,
            crate::models::CreateSacrificeRequest,
            crate::models::CreateTransferRequest,
            crate::models::VetEvaluateTransferRequest,
            crate::models::AssignTransferPlanRequest,
            crate::models::RejectTransferRequest,
            crate::models::DataBoundaryResponse,
            // HR / 通知 / 稽核
            crate::models::ClockInRequest,
            crate::models::CreateLeaveRequest,
            crate::models::CreateOvertimeRequest,
            // 產品管理
            crate::models::Product,
            crate::models::ProductStatus,
            crate::models::ProductCategory,
            crate::models::ProductUomConversion,
            crate::models::CreateProductRequest,
            crate::models::UpdateProductRequest,
            crate::models::UomConversionInput,
            crate::models::ProductQuery,
            crate::models::ProductWithUom,
            crate::models::CreateCategoryRequest,
            crate::models::ProductImportResult,
            crate::models::ProductImportErrorDetail,
            crate::models::ProductImportPreviewResult,
            crate::models::ProductImportPreviewRow,
            crate::models::CreateProductWithSkuRequest,
            // SKU
            crate::models::CategoriesResponse,
            crate::models::CategoryOption,
            crate::models::SubcategoriesResponse,
            crate::models::GenerateSkuRequest,
            crate::models::GenerateSkuResponse,
            crate::models::ValidateSkuRequest,
            crate::models::ValidateSkuResponse,
            crate::models::SkuPreviewRequest,
            crate::models::SkuPreviewResponse,
            crate::models::SkuSegment,
            crate::models::PackInfo,
            // 合作夥伴管理
            crate::models::Partner,
            crate::models::PartnerType,
            crate::models::SupplierCategory,
            crate::models::CustomerCategory,
            crate::models::CreatePartnerRequest,
            crate::models::UpdatePartnerRequest,
            crate::models::PartnerQuery,
            crate::models::GenerateCodeResponse,
            crate::models::PartnerImportResult,
            crate::models::PartnerImportErrorDetail,
            // 單據管理
            crate::models::DocType,
            crate::models::DocStatus,
            crate::models::Document,
            crate::models::DocumentLine,
            crate::models::CreateDocumentRequest,
            crate::models::DocumentLineInput,
            crate::models::UpdateDocumentRequest,
            crate::models::DocumentQuery,
            crate::models::DocumentWithLines,
            crate::models::DocumentLineWithProduct,
            crate::models::DocumentListItem,
            crate::models::PoReceiptStatus,
            crate::models::PoReceiptItem,
            // 儲位管理
            crate::models::LocationType,
            crate::models::StorageLocation,
            crate::models::StorageLocationWithWarehouse,
            crate::models::CreateStorageLocationRequest,
            crate::models::UpdateStorageLocationRequest,
            crate::models::StorageLayoutItem,
            crate::models::UpdateStorageLayoutRequest,
            crate::models::StorageLocationQuery,
            crate::models::StorageLocationInventoryItem,
            crate::models::UpdateStorageLocationInventoryItemRequest,
            crate::models::CreateStorageLocationInventoryItemRequest,
            // 報表／會計／治療藥物
            crate::handlers::CreateApPaymentRequest,
            crate::handlers::CreateArReceiptRequest,
            crate::models::TreatmentDrugOption,
            crate::models::CreateTreatmentDrugRequest,
            crate::models::UpdateTreatmentDrugRequest,
            crate::models::ImportFromErpRequest,
        )
    ),
    modifiers(),
    tags(
        (name = "監控", description = "健康檢查、Prometheus 指標、Web Vitals"),
        (name = "認證", description = "登入、登出、Token 重整、密碼管理"),
        (name = "使用者管理", description = "使用者 CRUD、密碼重設、模擬登入"),
        (name = "角色權限", description = "角色 CRUD、權限查詢"),
        (name = "設施管理", description = "物種、設施、棟舍、區域、欄位、部門管理"),
        (name = "倉儲管理", description = "倉庫 CRUD"),
        (name = "計畫書管理", description = "專案 CRUD、狀態變更、版本、活動歷程、Co-Editor"),
        (name = "審查管理", description = "審查委員指派、審查意見、草稿、獸醫審查表"),
        (name = "電子簽章", description = "犧牲／觀察／安樂死／轉讓／計畫書簽章與附註 (GLP)"),
        (name = "動物管理", description = "動物 CRUD、依欄位查詢、批次分配、獸醫已讀、事件歷程"),
        (name = "動物子模組", description = "觀察/手術/體重/疫苗/犧牲/病理/轉讓"),
        (name = "HR 出勤", description = "出勤列表、打卡"),
        (name = "HR 請假", description = "請假列表、建立"),
        (name = "HR 加班", description = "加班列表、建立"),
        (name = "通知", description = "通知列表、未讀數"),
        (name = "稽核管理", description = "活動日誌、登入事件、儀表板"),
        (name = "產品管理", description = "產品 CRUD、分類、匯入、SKU 建立"),
        (name = "SKU", description = "SKU 分類、子分類、產生、驗證、預覽"),
        (name = "合作夥伴管理", description = "夥伴 CRUD、匯入、代碼產生"),
        (name = "單據管理", description = "單據 CRUD、提交、核准、取消"),
        (name = "儲位管理", description = "儲位 CRUD、庫存、調撥、代碼產生"),
        (name = "報表", description = "庫存現況、流水、採購/銷貨明細、成本彙總、血液檢查"),
        (name = "會計", description = "會計科目、試算表、傳票、AP/AR 帳齡、付款/收款"),
        (name = "治療藥物", description = "治療方式藥物選項 CRUD、ERP 匯入"),
    ),
    security(
        ("bearer" = [])
    )
)]
pub struct ApiDoc;
